export default {
  CREATE_CLUSTER: "CREATE_CLUSTER",
  CREATE_CLUSTER_FAILED: "CREATE_CLUSTER_FAILED",
  MENU_SELECT: "MENU_SELECT",
  GET_LOOKUP_OPTIONS_DATA: "GET_LOOKUP_OPTIONS_DATA",
  GET_LOOKUP_OPTIONS_DATA_FAILED: "GET_LOOKUP_OPTIONS_DATA_FAILED",
};
