export default {
  CREATE_CLUSTER_SUCCESS: "CREATE_CLUSTER_SUCCESS",
  CREATE_CLUSTER_FAILED: "CREATE_CLUSTER_FAILED",
  MENU_SELECTED: "MENU_SELECTED",
  GET_LOOKUP_OPTIONS_DATA_SUCCESS: "GET_LOOKUP_OPTIONS_DATA_SUCCESS",
  GET_LOOKUP_OPTIONS_DATA_FAILED: "GET_LOOKUP_OPTIONS_DATA_FAILED",
};
